---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице товара и в каталоге пользователь должен видеть название, рейтинг, цену со скидкой и без нее.
  - После добавления товара в Корзину из Каталога товаров, пользователь должен остаться на текущей странице для продолжения покупок
  - У пользователя должна быть возможность вернуться из Корзиным к Каталогу товаров для продолжения покупок
  - Пользователь должен иметь возможность удалять товар из корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
    - Сайт должен быть SPA-приложением, которое не перезагружает страницу
implicit:
  - У пользователя не должно быть возможности добавить в корзину товар, которого нет в наличии
  - Значение цены товара должно быть больше нуля, цена не должна быть отрицательной
  - Цена товара по акции или со скидкой должна быть меньше значения цены товара без скидки
  - Пользователь должен иметь возможность редактировать количество товара в корзине
  - Пользователь должен видеть сообщение об использовании cookie на сайте магазина
  - В шапке сайта должна быть ссылка на форму обратной связи
  - Пользователь должен иметь возможность выбора валюты отображения цены и общей стоимости товаров
  - Пользователь должен видеть в корзине список добавленных товаров с указанием цены, количества и стоимости по каждому виду товара, так же должна быть показана общая сумма заказа
  - После успешного оформления заказа, список товаров в корзине должен обнуляться
  - После успешного оформления заказа пользователь имеет возможность перейти на страницу оплаты заказа